# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Madhava Reddy V M
tagline:             'Curiouser and Curiouser! '
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 vmgmreddy.github.io
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Madhava Reddy V M
  url:               vmgmreddy.github.io
  email:             vmgmreddy.cse17@iitbhu.ac.in

# Custom vars
version:             1.0.0

# Disqus Setup
layout: default
comments: true
disqus:
    shortname: vmgmreddy-github-io
